version: '3.8'

services:
    # PHP-FPM with Nginx container for running Laravel and PHPUnit
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        ports:
            - "80:80" # Expose container port 80 to host port 80

networks:
    laravel_network:
        driver: bridge
